name: Build OCI Image with .NET 6
on:
  push: 
    branches: [main]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devopenspace2023
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore DemoApp/Server/src/Server.csproj
      - name: Build
        run: dotnet build --no-restore DemoApp/Server/src/Server.csproj
      - name: Publish
        run: dotnet publish --no-build DemoApp/Server/src/Server.csproj
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
