name: demo-10.1 jobs transfer data (cross OS)
on:
  push: 
    branches: [main]
jobs:
  jobSource:
    runs-on: ubuntu-latest
    steps:
      - name: step-1 Name
        id: step-1
        run: echo "varInStep=hello world" >> $GITHUB_OUTPUT
    outputs:
      greetings: ${{ steps.step-1.outputs.varInStep }}
  jobTarget:
    runs-on: windows-latest
    needs: jobSource
    steps:
      - name: step-2 Name
        id: step-2
        run: echo ${{ needs.jobSource.outputs.greetings }}
